---
title: "Rice's Whale Vessel Risk Analysis by Owner in Gulf of America"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## Vessel Presence

- source: [benioff-ocean-initiative.gulf_of_mexico_2023.vessel_presence_bymmsi_10_v1](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1sbenioff-ocean-initiative!2sgulf_of_mexico_2023)


```{r}
# Install and load required packages
librarian::shelf(
  arrow, bigrquery, dplyr, ggplot2, glue, terra, viridis)

# mem.maxVSize()
# [1] 24576 # Mb

dir_data          <- "~/My Drive/projects/ricei/data"
vesselpresence_bq <- "benioff-ocean-initiative.gulf_of_mexico_2023.vessel_presence_bymmsi_10_v1"
vesselinfo_bq     <- "benioff-ocean-initiative.gulf_of_mexico_2023.ihs_data_all"

# Authentication - this will prompt for authentication in browser
# If you're running this in an automated environment, consider using service account authentication
bq_auth()
```

```{r}
# Define project and dataset information
# project_id <- "benioff-ocean-initiative"
# dataset_id <- "gulf_of_mexico_2023"
# table_id   <- "vessel_presence_bymmsi_10_v1"

# Define SQL query
# Note: Using partition filtering on date for efficiency
# sql <- glue("
#   SELECT 
#     cell_ll_lat,
#     cell_ll_lon,
#     dist_travelled_km,
#     avg_speed_knots,
#     CASE 
#       WHEN avg_speed_knots <= 10 THEN '0-10'
#       WHEN avg_speed_knots <= 12 THEN '10-12'
#       WHEN avg_speed_knots <= 15 THEN '12-15'
#       ELSE '15+'
#     END AS speed_bin
#   FROM `{project_id}.{dataset_id}.{table_id}`
#   WHERE date BETWEEN '2023-01-01' AND '2023-12-31'
#     AND cell_ll_lat IS NOT NULL
#     AND cell_ll_lon IS NOT NULL
#     AND dist_travelled_km IS NOT NULL
#     AND avg_speed_knots IS NOT NULL")

# data <- bq_table_download(bq_project_query(project_id, sql))
# Error in `bq_post()`:
# ! Access Denied: Project benioff-ocean-initiative: User does not have
#   bigquery.jobs.create permission in project benioff-ocean-initiative.
#   [accessDenied]
# bq_tbl <- bq_table(project_id, dataset_id, table_id)

for (tbl_bq in c(vesselpresence_bq, vesselinfo_bq)){
  # tbl_bq = vesselpresence_bq # 53 chunks
  # tbl_bq = vesselinfo_bq     # 1  chunk

  message(glue("Fetching data from BigQuery: {tbl_bq} ~ {Sys.time()}"))
  p <- unlist(strsplit(tbl_bq, "[.]"))
  
  bq_tbl <- bq_table(p[1], p[2], p[3])
  
  # iterate over 1 gb chunks, given number of rows per chunk
  gb_tbl   <- as.vector(bq_table_size(bq_tbl)) / 1000^3
  nrow_tbl <- bq_table_nrow(bq_tbl)
  gb_i     <- 1                         # 1 GB chunks
  n_i      <- ceiling(gb_tbl   / gb_i)  # number of chunks;          53
  nrow_i   <- ceiling(nrow_tbl / n_i )  # rows per chunk;    16,934,451
  
  row_beg <- 0
  for (i in 1:n_i){ # i = 1
    
    pq <- glue("{dir_data}/raw/ships/{p[2]}/{p[3]}/chunk_{sprintf('%02d', i)}.parquet")
    dir.create(dirname(pq), recursive = T, showWarnings = F)
    
    if (file.exists(pq)) {
      row_beg <- row_beg + nrow_i
      next
    }
    
    message(glue("- reading chunk {i}: row {row_beg} to {min(row_beg + nrow_i, nrow_tbl)} ~ {Sys.time()}"))
    # reading chunk 1: 0 to 16934451 ~ 2025-04-14 18:16:55.603398
    # reading chunk 2: 16934451 to 33868902 ~ 2025-04-14 18:17:44.441115
    # reading chunk 36: 592705785 to 609640236 ~ 2025-04-14 21:40:13.27480
    # reading chunk 49: 812853648 to 829788099 ~ 2025-04-14 21:50:19.7238173
    data <- bq_table_download(
      bq_tbl,
      start_index = row_beg,
      n_max       = nrow_i)
    # Downloading first chunk of data.Received 127,988 rows in the first chunk.
    # Downloading the remaining 16,806,463 rows in 176 chunks of (up to) 95,991 rows.
    
    message(glue("-   writing chunk {i} to {basename(pq)} ~ {Sys.time()}"))
    # writing chunk 1 to chunk_01.parquet ~ 2025-04-14 18:17:41.160944
    write_parquet(data, pq) # compression = default_parquet_compression() = "snappy"
    
    row_beg <- row_beg + nrow_i
  }
}
```

- <https://arrow.apache.org/docs/r/articles/arrow.html#multi-file-data-sets>

TODO:

- [ ] raster of GoA vs global
- [ ] duckdb comparison of dates
  - [R Client – DuckDB](https://duckdb.org/docs/stable/clients/r.html)\
  
    ```r
    # Establish a set of Parquet files
    dbExecute(con, "COPY flights TO 'dataset' (FORMAT parquet, PARTITION_BY (year, month))")
  
    # Summarize the dataset in DuckDB to avoid reading 12 Parquet files into R's memory
    tbl(con, "read_parquet('dataset/**/*.parquet', hive_partitioning = true)") |>
      filter(month == "3") |>
      summarise(delay = mean(dep_time, na.rm = TRUE)) |>
      collect()
    ```
  - [Querying Parquet with Precision Using DuckDB – DuckDB](https://duckdb.org/2021/06/25/querying-parquet.html)\
    consider paritioning, ordering, indexing 
    - [Working with multi-file data sets • Arrow R Package](https://arrow.apache.org/docs/r/articles/dataset.html#partitioning-performance-considerations)
    
```{r}
#| label: setup_duckdb

librarian::shelf(
  dplyr, duckdb, glue, readr)

dir_tbl <- "/Users/bbest/Library/CloudStorage/GoogleDrive-ben@ecoquants.com/My Drive/projects/ricei/data/raw/ships/gulf_of_mexico_2023/"
goa_db  <- glue("{dir_tbl}/goa.db")

# Connect to DuckDB
con <- dbConnect(duckdb(), dbdir = goa_db, read_only = F)
```

```{r load_duckdb}

# Load Parquet files into DuckDB
dbExecute(con, glue(
  "CREATE TABLE ship_cell AS SELECT * FROM read_parquet('{dir_tbl}/vessel_presence_bymmsi_10_v1/*.parquet')") )
# nrows: 897,525,872

dbExecute(con, glue(
  "CREATE TABLE ship AS SELECT * FROM read_parquet('{dir_tbl}/ihs_data_all/*.parquet')") )
# nrows:     236,134

# Load Parquet files into DuckDB
dbExecute(con, glue(
  "CREATE OR REPLACE TABLE company AS SELECT * FROM read_csv('{dir_tbl}/companies.csv')") )
# nrows:          16

# glue("{dir_tbl}/companies.csv") |> read_csv()

# dbExecute(con, "ALTER TABLE vessel_presence RENAME TO ship_cell")
# dbExecute(con, "ALTER TABLE vessel_ihs RENAME TO ship")

# Query the data
# tbl(con, "ship_cell")
# tbl(con, "ship")
#    imo_lr_ihs_no      mmsi name_of_ship         callsign ship_type group_owner technical_manager shipmanager registered_owner operator
#            <int>     <int> <chr>                <chr>    <chr>     <chr>       <chr>             <chr>       <chr>            <chr>   
#  1       8352526 244184361 TENACIOUS            PH9945   Towing/P… CFT         CFT               CFT         CFT              CFT     
#  2       9582893 244700202 AURISSE              PB7611   Chemical… CFT         CFT               CFT         CFT              CFT     
#  3       9026148 345070136 PLATTE RIVER         XCCJ8    Crew Boat CSP         CSP               CSP         HSP              CSP     
#  4       8600909 205114000 FELIX ANTOIE TSHISE… ORKO     Trailing… CVM         CVM               CVM         CVM              CVM     
#  5       9314129 210761000 SALT LAKE CITY       C4DS2    Bulk Car… Diana Ship… DWM               DWM         Marfort Navigat… Uniper …
#  6       9314129 210761000 SALT LAKE CITY       C4DS2    Bulk Car… OceanPal I… DWM               DWM         Marfort Navigat… Five Oc…
#  7       9286633 311773000 PROTEFS              C6TT6    Bulk Car… OceanPal I… DWM               DWM         Cypres Enterpri… HSL Shi…
#  8       9297929 311912000 CALIPSO              C6UH2    Bulk Car… Diana Ship… DWM               DWM         Darien Compania… Transgr…
#  9       9297929 311912000 CALIPSO              C6UH2    Bulk Car… Diana Ship… DWM               DWM         Darien Compania… Transgr…
# 10       9297929 311912000 CALIPSO              C6UH2    Bulk Car… Diana Ship… DWM               DWM         Darien Compania… Transgr…
# # ℹ more rows
# # ℹ 7 more variables: operator_code <int>, registered_owner_code <int>, chartered_from <chr>, source_table <chr>,
# #   updated_date <date>, length_m <dbl>, weight_gt <int>

tbl(con, "ship") |> 
  group_by(mmsi) |> 
  summarize(
    n = n()) |> 
  filter(n > 1) |> 
  arrange(desc(n)) |> 
  collect()
# # A tibble: 28,107 × 2
#         mmsi     n
#        <int> <dbl>
#  1 305293000    27
#  2 636015872    27
#  3 538002591    27
d_dupe1 <- tbl(con, "ship") |> 
  filter(mmsi == 305293000) |> 
  relocate(updated_date) |> 
  arrange(desc(updated_date)) |> 
  collect()
View(d_dupe1)
```

```{r}
sc_date_n <- tbl(con, "ship_cell") |> 
  filter(
    cell_ll_lon >= !!b[1],
    cell_ll_lat >= !!b[2],
    cell_ll_lon <= !!b[3],
    cell_ll_lat <= !!b[4]) |>
  group_by(date) |> 
  summarize(
    n = n()) |> 
  arrange(date) |> 
  collect()
# View(sc_date_n)
# surprising:
# - gaps in dates (59 days with data / 365 days)
# - spikes in data with 3 orders of magnitude diff, 
#   eg 2023-01-29 127,908 to 2023-01-31 123,249,963

librarian::shelf(dygraphs)

dygraph(sc_date_n, main = "Ship Presence in Gulf by Date") |> 
  dySeries("n", label = "Number of Records") |> 
  dyAxis("y", label = "Records") |> 
  dyRangeSelector() |> 
  dyOptions(
    strokeWidth = 1, 
    drawPoints  = T,
    pointSize   = 2)
```

```{r}
librarian::shelf(stringr)

d_c <- tbl(con, "company") |> 
  collect()

for (i in 1:nrow(d_c)){ # i = 1
  company         <- d_c$company[i]
  operator_lookup <- d_c$operator_lookup[i]
  
  message(company)
  
  d <- dbGetQuery(
    con,
    glue("
         SELECT operator, operator_code FROM ship 
         WHERE
           operator ILIKE '%{company}%'
         ")) |> 
    collect() |> 
    tibble()
  message(glue("  {company}: "), nrow(d))
  d |> table() |> print()
  
  d2 <- dbGetQuery(
    con,
    glue("
         SELECT operator, operator_code FROM ship 
         WHERE
           operator ILIKE '%{operator_lookup}%'
         ")) |> 
    collect() |> 
    tibble()
  message(glue("  {operator_lookup}: "), nrow(d2),"\n")
  d2 |> table() |> print()
}

#                                operator_code
# operator                         387 4427 28896 194433 259393 1826240 6514732
#   CMA CGM Asia Pacific Ltd         0    0     2      0      0       0       0
#   CMA CGM Asia Shipping Pte Ltd    0    0     0      0      0       3       0
#   CMA CGM Philippines Shipping     0    0     0      0      0       0       1
#   CMA CGM SA The French Line    1544    0     0   1225      0       0       0
#   Containerships-CMA CGM GmbH      0    1     0      0     13       0       0
```



```{r grid}
librarian::shelf(
  here, janitor, leaflet, sf, terra)

dir_raw    <- "~/My Drive/projects/ricei/data/raw" # Google Drive
whales_shp <- glue("{dir_raw}/whales/Rices_Whale_Monthly_Density.shp")

# hex of whales
h_w <- read_sf(whales_shp) |>    # nrow: 42,908
  clean_names() |>
  mutate(
    hexid = as.integer(hexid),
    across(where(is.numeric), ~na_if(., -9999))) |> 
  st_transform(4326)

bb <- st_bbox(h_w) |> 
  st_as_sfc()
#      xmin      ymin      xmax      ymax 
# -97.89111  18.12907 -80.33379  30.77506

# h_w <- h_w |>   
#   filter(!if_all(Jan_n:Dec_cv, is.na)) # nrow: 33,650
# st_bbox(h_w)

leaflet() |> 
  addProviderTiles("Esri.OceanBasemap") |> 
  addPolygons(
    data        = h_w,
    fillColor   = "blue",
    fillOpacity = 0.5,
    color       = "black",
    weight      = 1,
    opacity     = 1,
    label       = ~glue("Hex ID: {HEXID}")) # |> 
  # setView(lng = -89, lat = 25, zoom = 5) # zoom: 5

r_10 <- terra::rast(
  ext(h_w),
  resolution = c(0.1, 0.1)) # 10th degree resolution

# r_tif <- here("data/rasters.tif")
# r <- rast(r_tif)
# names(r)

b <- st_bbox(h_w) |> as.numeric()

d_cell_n <- tbl(con, "ship_cell") |> 
  filter(
    cell_ll_lon >= !!b[1],
    cell_ll_lat >= !!b[2],
    cell_ll_lon <= !!b[3],
    cell_ll_lat <= !!b[4]) |>
  group_by(cell_ll_lon, cell_ll_lat) |> 
  summarize(n = n()) |> 
  collect()  # 16,532 × 3

r_n <- d_cell_n |> 
  vect(
    geom = c("cell_ll_lon", "cell_ll_lat"),
    crs = "EPSG:4326", keepgeom = T) |>
  terra::rasterize(
    r_10,
    field = "n",
    fun   = "sum")

names(r_n) <- 

plet(log10(r_n), tiles="Esri.OceanBasemap", main = "log10(# ship<br>presence<br>records), 2023<br>(log10)")
providers$
librarian::shelf(
  tidyr)

d_w <- h_w |>
  st_drop_geometry() |> 
  pivot_longer(
    !hexid, 
    names_to  = "metric",
    values_to = "value") |> 
  filter(!is.na(value)) |> 
  separate_wider_delim(
    metric, "_", 
    names = c("month", "metric"))

d_w_avg <- d_w |> 
  group_by(
    hexid, metric) |> 
  summarize(
    value = mean(value),
    .groups = "drop")
    
d_w_all <- bind_rows(
  d_w_avg |> 
    mutate(
      timespan = "avg"),
  d_w |> 
    mutate(
      timespan = "month")) |> 
  select(hexid, timespan, month, metric, value)

r_w <- d_cell_n |> 
  vect(
    geom = c("cell_ll_lon", "cell_ll_lat"),
    crs = "EPSG:4326", keepgeom = T) |>
  terra::rasterize(
    r_10,
    field = "n",
    fun   = "sum")
    
    sf_use_s2(F)
    ply_whales <- hex_whales |> 
      select(hex_id) |> 
      filter(hex_id %in% unique(tbl_whales_avg$hex_id)) |> 
      st_intersection(
        plys_study) |> 
      group_by(
        hex_id) |> 
      summarize() |> 
      mutate(
        area_km2 = st_area(geometry) |> set_units("km^2"))
    sf_use_s2(T)
```

```{r co_cell}
d_company <- tbl(con, "company") |> 
  collect()

co <- d_company$company[1]
op <- d_company$operator_lookup[1]

tbl(con, "cell") |> 
  left_join(
    tbl(con, "ship_cell"),
    by = c("cell_ll_lon", "cell_ll_lat")) |>

```
  

```{r}
#| label: summarize

vesselpresence_bq <- "benioff-ocean-initiative.gulf_of_mexico_2023.vessel_presence_bymmsi_10_v1"

dir_vpres <- glue("{dir_data}/raw/ships/gulf_of_mexico_2023/vessel_presence_bymmsi_10_v1")
d_vpres <- open_dataset(dir_vpres)
head(d_vpres) |> collect()

# TODO: sort (date, mmsi, cell_ll_lon, cell_ll_lat) and save as a single parquet file
d_vpres_date <- d_vpres |> 
  group_by(date) |> 
  summarize(
    n                 = n(),
    dist_travelled_km = sum(dist_travelled_km, na.rm = T),
    avg_speed_knots   = mean(avg_speed_knots, na.rm = T)) |>
  arrange(date) |> 
  collect()
# d_vpres_date |> View()
#   date       cell_ll_lat cell_ll_lon mmsi      hours dist_travelled_km avg_speed_knots
#   <date>           <dbl>       <dbl> <chr>     <dbl>             <dbl>           <dbl>
# 1 2023-10-07       -42.5       -62.8 636022759 0.083              2.01           13.4 
# 2 2023-10-07       -41.3       -62.1 636022759 0.083              2.08           13.7 
# 3 2023-10-07       -38.6       144.  352002415 0.083              1.47            9.58
# 4 2023-10-07       -38.3       145.  352002415 0.083              1.93           13.1 
# 5 2023-10-07       -38.1       144.  352002415 0.083              1.18            7.66
# 6 2023-10-07       -37.5       102.  994210602 0.083              1.22            7.91

d_vpres_ll <- d_vpres |> 
  group_by(cell_ll_lon, cell_ll_lat) |> 
  summarize(
    n                 = n(),
    dist_travelled_km = sum(dist_travelled_km, na.rm = T),
    avg_speed_knots   = mean(avg_speed_knots, na.rm = T)) |>
  arrange(cell_ll_lon, cell_ll_lat) |> 
  collect()

d_vpres_ll <- d_vpres_ll |>
  
  diff(round(d_vpres_ll$cell_ll_lon, 1)) |> table()
range(d_vpres_ll$cell_ll_lon) # -180.0  179.9
range(d_vpres_ll$cell_ll_lat) # -89.0  89.8
  

# Process the data
message("Processing data...")
# Aggregate by cell and speed bin
raster_data <- data |> 
  group_by(cell_ll_lon, cell_ll_lat, speed_bin) |> 
  summarize(total_dist = sum(dist_travelled_km, na.rm = TRUE)) |> 
  ungroup()

# Get unique coordinates to determine raster dimensions
unique_lons <- sort(unique(raster_data$cell_ll_lon))
unique_lats <- sort(unique(raster_data$cell_ll_lat))

# Determine cell resolution based on data
lon_res <- min(diff(unique_lons))
lat_res <- min(diff(unique_lats))

# Create empty rasters for each speed bin
speed_bins <- c("0-10", "10-12", "12-15", "15+")
rasters <- list()

# Define raster extent
e <- extent(
  min(unique_lons) - (lon_res/2),
  max(unique_lons) + (lon_res/2),
  min(unique_lats) - (lat_res/2),
  max(unique_lats) + (lat_res/2)
)

message("Creating rasters...")
for (bin in speed_bins) {
  # Filter data for this speed bin
  bin_data <- raster_data %>% filter(speed_bin == bin)
  
  # Create an empty raster
  r <- raster(e, resolution = c(lon_res, lat_res))
  
  # Populate the raster
  for (i in 1:nrow(bin_data)) {
    cell <- cellFromXY(r, c(bin_data$cell_ll_lon[i], bin_data$cell_ll_lat[i]))
    r[cell] <- bin_data$total_dist[i]
  }
  
  # Store in list
  rasters[[bin]] <- r
}

# Create a combined raster
combined_raster <- rasters[["0-10"]] # Initialize with first raster
combined_raster[is.na(combined_raster)] <- 0 # Replace NA with 0

# Add all bins with proper names
names(combined_raster) <- "0-10 knots"

for (bin in speed_bins[-1]) {
  r <- rasters[[bin]]
  r[is.na(r)] <- 0
  combined_raster <- addLayer(combined_raster, r)
}
names(combined_raster)[2:4] <- c("10-12 knots", "12-15 knots", "15+ knots")

# Save the raster to file
writeRaster(combined_raster, "speed_binned_distances.tif", overwrite=TRUE)

# Plot the results
message("Creating visualization...")
par(mfrow=c(2,2))
for (i in 1:4) {
  plot(combined_raster[[i]], main=names(combined_raster)[i],
       col=viridis(100), zlim=c(0, max(maxValue(combined_raster))),
       axes=TRUE)
}

# Create a stack plot for all layers
plot(combined_raster, col=viridis(100))

message("Done! Results saved as 'speed_binned_distances.tif'")
```

You can add options to executable code like this

```{r db_disconnect}
# Disconnect from DuckDB
dbDisconnect(con, shutdown = TRUE)
```
